FROM jenkins:v1

MAINTAINER fjw

ADD node.tar.xz /usr/local/
ADD apache-maven-3.3.9-bin.tar.gz /usr/local

ENV NODE_HOME /usr/local/node/bin
ENV PATH /usr/local/node/bin:/bin:/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/apache-maven-3.3.9/bin
